import { promises as fs } from 'node:fs';
import { join } from 'node:path';
import fse from 'fs-extra';
import { ManifestSchema } from '@spectrl/schema';
import { CLIError, ExitCode } from '../errors.js';

export interface CatalogEntry {
  name: string;
  version: string;
  type: 'spec' | 'power';
  description: string;
  purpose: string;
}

/**
 * Generate a markdown catalog table from catalog entries.
 *
 * Produces a markdown table with columns: Name, Version, Type, Description, When to Use.
 * The "When to Use" column uses agent.purpose if available, falls back to description,
 * then empty string.
 */
export function generateCatalogMarkdown(entries: CatalogEntry[]): string {
  const header = [
    '<!-- Auto-generated by Spectrl. Do not edit manually. -->',
    '',
    '# Spectrl Catalog',
    '',
  ].join('\n');

  if (entries.length === 0) {
    return `${header}| Name | Version | Type | Description | When to Use |\n| ---- | ------- | ---- | ----------- | ----------- |\n`;
  }

  // Compute column widths for alignment
  const cols = {
    name: Math.max(4, ...entries.map((e) => e.name.length)),
    version: Math.max(7, ...entries.map((e) => e.version.length)),
    type: Math.max(4, ...entries.map((e) => e.type.length)),
    description: Math.max(11, ...entries.map((e) => e.description.length)),
    purpose: Math.max(11, ...entries.map((e) => e.purpose.length)),
  };

  const pad = (s: string, len: number) => s.padEnd(len);

  const headerRow = `| ${pad('Name', cols.name)} | ${pad('Version', cols.version)} | ${pad('Type', cols.type)} | ${pad('Description', cols.description)} | ${pad('When to Use', cols.purpose)} |`;
  const separatorRow = `| ${'-'.repeat(cols.name)} | ${'-'.repeat(cols.version)} | ${'-'.repeat(cols.type)} | ${'-'.repeat(cols.description)} | ${'-'.repeat(cols.purpose)} |`;

  const rows = entries.map(
    (e) =>
      `| ${pad(e.name, cols.name)} | ${pad(e.version, cols.version)} | ${pad(e.type, cols.type)} | ${pad(e.description, cols.description)} | ${pad(e.purpose, cols.purpose)} |`,
  );

  return [header, headerRow, separatorRow, ...rows, ''].join('\n');
}

/**
 * Generate the catalog file at `.spectrl/catalog.md`.
 *
 * Reads the project index from `.spectrl/spectrl-index.json`, reads each installed
 * manifest from `.spectrl/specs/{key}/spectrl.json`, and writes the catalog.
 *
 * Entries with unreadable manifests are skipped with a warning.
 */
export async function generateCatalog(cwd: string): Promise<void> {
  const spectrlDir = join(cwd, '.spectrl');
  const indexPath = join(spectrlDir, 'spectrl-index.json');

  // Read project index
  let indexData: unknown;
  try {
    const content = await fs.readFile(indexPath, 'utf-8');
    indexData = JSON.parse(content);
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      // No index yet — write an empty catalog
      const catalogPath = join(spectrlDir, 'catalog.md');
      await fse.ensureDir(spectrlDir);
      await fs.writeFile(catalogPath, generateCatalogMarkdown([]), 'utf-8');
      return;
    }
    throw new CLIError(
      `Failed to read project index: ${(error as Error).message}`,
      ExitCode.IO_ERROR,
    );
  }

  // The index is a Record<"name@version", { source, hash }>
  if (typeof indexData !== 'object' || indexData === null || Array.isArray(indexData)) {
    throw new CLIError('Invalid project index format', ExitCode.VALIDATION_ERROR);
  }

  const specKeys = Object.keys(indexData as Record<string, unknown>);
  const entries: CatalogEntry[] = [];

  for (const specKey of specKeys) {
    // Derive the directory name used by the install command
    // Public specs use "username-name@version", local specs use "name@version"
    const specsDir = join(spectrlDir, 'specs');

    // Try the key as-is first (local: "name@version"), then with slash replaced (public: "user/name@version" → "user-name@version")
    const candidateDirs = [join(specsDir, specKey), join(specsDir, specKey.replace('/', '-'))];

    // Also try the source path from the index (registry spec root for local specs)
    const indexEntry = (indexData as Record<string, unknown>)[specKey];
    if (
      indexEntry &&
      typeof indexEntry === 'object' &&
      'source' in indexEntry &&
      typeof (indexEntry as { source: unknown }).source === 'string'
    ) {
      const sourcePath = (indexEntry as { source: string }).source;
      // Only add local paths (not http/https URLs)
      if (!sourcePath.startsWith('http://') && !sourcePath.startsWith('https://')) {
        candidateDirs.push(sourcePath);
      }
    }

    let manifestData: unknown = null;
    for (const dir of candidateDirs) {
      const manifestPath = join(dir, 'spectrl.json');
      try {
        const content = await fs.readFile(manifestPath, 'utf-8');
        manifestData = JSON.parse(content);
        break;
      } catch {
        // Try next candidate
      }
    }

    if (manifestData === null) {
      // Could not read manifest — skip with warning
      console.warn(
        `[spectrl] Warning: could not read manifest for ${specKey}, skipping in catalog`,
      );
      continue;
    }

    const parseResult = ManifestSchema.safeParse(manifestData);
    if (!parseResult.success) {
      console.warn(
        `[spectrl] Warning: invalid manifest for ${specKey}: ${parseResult.error.issues[0].message}, skipping in catalog`,
      );
      continue;
    }

    const manifest = parseResult.data;

    // Parse name and version from specKey ("name@version" or "user/name@version")
    const atIdx = specKey.lastIndexOf('@');
    const name = atIdx !== -1 ? specKey.slice(0, atIdx) : specKey;
    const version = atIdx !== -1 ? specKey.slice(atIdx + 1) : manifest.version;

    // Fallback logic: purpose → description → empty string
    const description = manifest.description ?? '';
    const purpose = manifest.agent?.purpose ?? description;

    entries.push({
      name,
      version,
      type: manifest.type,
      description,
      purpose,
    });
  }

  // Write catalog
  const catalogPath = join(spectrlDir, 'catalog.md');
  try {
    await fs.writeFile(catalogPath, generateCatalogMarkdown(entries), 'utf-8');
  } catch (error) {
    throw new CLIError(
      `Failed to generate catalog: ${(error as Error).message}`,
      ExitCode.IO_ERROR,
    );
  }
}
